name = "noteapp"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "noteapp-db"
database_id = "366980e4-4ada-4adc-84f5-a1089da3b668"
